### ISSUE TITLE
POD Issues with Swift use_frameworks! keyword

### ISSUE THREAD

**Issue by ForGuru** [RestComm/restcomm-ios-sdk#512] opened 2016-11-24 05:52 UTC
I have tried to integrate POD in a project where I am using 

use_frameworks! keyword in pod file

it doesn't find some header files. We know that this is the known issue with PODS for a project with mixed languages (Swift and Objective C).

https://github.com/CocoaPods/CocoaPods/issues/4605

Have you been able to find a workaround for this situation ??

**Comment by TheEngineerz** [comment] 2016-11-24 05:58
@atsakiridis Facing the same issue

**Comment by atsakiridis** [comment] 2016-11-24 08:30
Managed to reproduce this too :(. I'm afraid the way to properly fix that is to address the issue in CocoaPods, so that headers are picked up correctly. So I would suggest that you post in CocoaPods issue to try to push them to fix it.

A possible workaround could be to make the header files of Sofia SIP flat, and update the code in the Restcomm SDK to reference them correctly. The problem with that is that, is that it's difficult to automate, since when building Sofia using autotools the dirs are expected to be non flat. Will try to work on that when I find some free cycles.

Until either fix is ready you could use one of the workarounds found at CocoaPods/CocoaPods#4605 so that you can build successfully and not be blocked.

**Comment by ForGuru** [comment] 2016-11-24 09:01
@atsakiridis thanks 

How can I integrate previous version of sdk which was without pods in swift project, can guide me through it ??

**Comment by atsakiridis** [comment] 2016-11-24 10:10
You could try following the previous Quick Start Guide, that is before cocoapods were introduced, which references the respective SDK release. But keep in mind that it is obsolete.

**Comment by atsakiridis** [comment] 2016-11-24 10:18
Forgot to add a link to the prev guide, sorry: https://github.com/RestComm/Restcomm-Connect/blob/213e7450b8aa2f96982ca70737c51784a260a60f/restcomm/restcomm.docs/sources-asciidoc/src/main/asciidoc/sdks/restcomm-client-ios-sdk-quick-start.adoc

**Comment by ForGuru** [comment] 2016-11-24 13:32
@atsakiridis and @TheEngineerz  
I did a trick 

1- Created a Swift project and added the POD of Rest-comm
2- removed the use_frameworks! keyword
3- Built and it was success full

4- performed same action on my old project with use_frameworks! keyword
5- and there was an error as expected
6- I copied "${PODS_ROOT}/Headers/" from new project and manually placed in my old project "${PODS_ROOT}/Headers/"
7- Compiled and it did now testing other things 
8- Can we develop a script so it can copy all required files as I did manually ??

**Comment by atsakiridis** [comment] 2016-11-24 13:59
Yeah, this seems like on of the things the submitter of CocoaPods/CocoaPods#4605 did as a workaround. But I think it's going to be messy, having to build first without the offending cocoapod option and then building anew, but having kept the previous build somewhere so that we can copy the headers over... Its going to become unmanageable in no time :(

Any chance there are other workarounds in that issue that we could use?

**Comment by TheEngineerz** [comment] 2016-11-24 14:41
But @atsakiridis I think there is some other issues with Restcomm pods itself.

 I simply created a new project Init the Podfile like below
```
target 'TestRestComm' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  pod "restcomm-ios-sdk"
  # Pods for TestRestComm

end
```
Every thing go successfully but i am not able to

`import RestCommClient `

in my ViewController.swift. It gives me error that no such module exist

Using Xcode 8.1 and Swift 3.0. Please advice

![screen shot 2016-11-24 at 7 40 15 pm](https://cloud.githubusercontent.com/assets/5149947/20602178/ea4e8b5a-b27d-11e6-8eb6-723ad551b8fe.png)
![screen shot 2016-11-24 at 7 40 33 pm](https://cloud.githubusercontent.com/assets/5149947/20602180/eaf8dd12-b27d-11e6-9a59-db8201430d62.png)

**Comment by TheEngineerz** [comment] 2016-11-24 16:06
@atsakiridis  @ForGuru  I resolved my issue by creating Bridge header file and add this line

`#import <restcomm-ios-sdk/RestCommClient.h>`

Now everything is working fine.

**Comment by atsakiridis** [comment] 2016-11-24 16:30
Sounds great @TheEngineerz. So you 're able to integrate the Restcomm iOS SDK from Swift without using `use_frameworks!` in your Podfile?

**Comment by ForGuru** [comment] 2016-11-27 08:21
@atsakiridis @TheEngineerz  i am abele to integrate in swift and have made few test calls

Currently its not refreshing registrations following is the log error.

`Nov 27 13:17:03  MyTest[4631] <Error>: (sofsip_cli.mm:633) sofsip_handle_input_cb(), marking for restart, stackIsShuttingDown: 0`

**Comment by ForGuru** [comment] 2016-11-27 08:35
@atsakiridis  @TheEngineerz Sorry that was not it was due to running the event loop again.

But ree-registration has some issues.

**Comment by atsakiridis** [comment] 2016-11-28 11:09
@ForGuru let's keep the registration issue separate and discuss in the context of #513

**Comment by atsakiridis** [comment] 2016-11-28 11:09
Closing this as the issue isn't SDK related. The gist of this issue is the following for future reference:
- Restcomm iOS SDK works with Swift projects so long as there is no swift CocoaPod dependency introduced. If that happens the `use_frameworks!` needs to be used, but in that case you would stumble on CocoaPod issue: CocoaPods/CocoaPods#4605
- For Swift projects a bridging header might be needed

**Closed by atsakiridis** 2016-11-28 11:09 UTC
